# Nama alur kerja yang akan muncul di tab Actions di GitHub
name: Security Scan and Vercel Deployment

# Pemicu (trigger) untuk menjalankan alur kerja ini
on:
  # Memungkinkan alur kerja dijalankan secara manual dari UI GitHub
  workflow_dispatch: {}
  
  # Berjalan saat ada pull request ke branch main atau master
  pull_request:
    branches:
      - main
      - master
      
  # Berjalan saat ada push (commit) ke branch main atau master
  push:
    branches:
      - main
      - master

# Daftar pekerjaan (jobs) yang akan dieksekusi
jobs:
  # --- JOB 1: SEMGREP SCAN ---
  semgrep:
    name: Semgrep Security Scan
    runs-on: ubuntu-latest
    permissions:
      contents: read
    env:
      SEMGREP_APP_TOKEN: ${{ secrets.SEMGREP_APP_TOKEN }}
    container:
      image: semgrep/semgrep
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Run Semgrep scan
        run: semgrep ci

  # --- JOB 2: VERCEL DEPLOYMENT ---
  vercel:
    name: Build and Deploy to Vercel
    runs-on: ubuntu-latest
    needs: semgrep
    outputs:
      prod_url: ${{ steps.get_prod_url.outputs.prod_url }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # =================================================================
      # >> LANGKAH DIAGNOSTIK SEMENTARA <<
      # Tujuannya untuk melihat struktur folder proyek Anda.
      # =================================================================
      - name: Show Folder Structure
        run: ls -R
      # =================================================================
          
      - name: Setup Node.js v22
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          
      # Langkah ini sengaja dibiarkan agar kita bisa melihat output diagnostik.
      # Kemungkinan besar akan gagal, dan itu tidak apa-apa.
      - name: Install dependencies & build
        run: |
          npm install
          npm run build
          
      - name: Deploy to Vercel
        uses: amondnet/vercel-action@v25
        with:
          vercel-args: '--prod'
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID }}
          vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID }}
          
      - name: Get Production URL
        id: get_prod_url
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
          PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
        run: |
          RESPONSE=$(curl -s -H "Authorization: Bearer $VERCEL_TOKEN" "https://api.vercel.com/v9/projects/$PROJECT_ID/domains")
          URL=$(echo "$RESPONSE" | jq -r '.domains[0].name')
          echo "prod_url=https://$URL" >> $GITHUB_OUTPUT

  # --- JOB 3: ZAP SCAN ---
  zap:
    name: OWASP ZAP Baseline Scan
    runs-on: ubuntu-latest
    needs: vercel
    steps:
      - name: Run ZAP Baseline Scan
        run: |
          TIMESTAMP=$(date +%s)
          REPORT_NAME="zap-report-${TIMESTAMP}.html"
          REPORT_LOCATION="$HOME/zap-reports"
          TARGET_URL=${{ needs.vercel.outputs.prod_url }}
          echo "Scanning target: $TARGET_URL"
          echo "Report will be saved as: $REPORT_NAME"
          mkdir -p "$REPORT_LOCATION"
          docker run --rm --user root \
            -v "$REPORT_LOCATION":/zap/wrk \
            zaproxy/zap-stable \
            zap-baseline.py -t "$TARGET_URL" -r "$REPORT_NAME" -I
          echo "REPORT_NAME=${REPORT_NAME}" >> $GITHUB_ENV
          echo "REPORT_LOCATION=${REPORT_LOCATION}" >> $GITHUB_ENV
      - name: Upload ZAP HTML Report
        uses: actions/upload-artifact@v4
        with:
          name: zap-baseline-report
          path: ${{ env.REPORT_LOCATION }}/${{ env.REPORT_NAME }}
 