 # Nama alur kerja yang akan muncul di tab Actions di GitHub
name: Vercel Production Deployment

on:
  push:
    branches:
      - main
      - master
  pull_request:
    branches:
      - main
      - master

jobs:
  # Kita gabungkan semua jadi satu job untuk kesederhanaan
  deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest
    steps:
      # Langkah 1: Checkout kode (tanpa submodule)
      - name: Checkout code
        uses: actions/checkout@v4

      # Langkah 2: Setup Node.js
      - name: Setup Node.js v22
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          
      # Langkah 3: Install dependensi dan build
      - name: Install dependencies & build
        run: |
          npm install
          npm run build
          
      # Langkah 4: Deploy ke Vercel
      - name: Deploy to Vercel
        uses: amondnet/vercel-action@v25
        with:
          vercel-args: '--prod'
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID }}
          vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID }}
