name: '[DIAGNOSTIK] Lihat Struktur Folder'

on:
  push:
    branches:
      - main
      - master

jobs:
  investigasi:
    name: Investigasi Struktur Folder
    runs-on: ubuntu-latest
    steps:
      - name: Checkout kode dari repository
        uses: actions/checkout@v4

      # =================================================================
      # >> LANGKAH PALING PENTING <<
      # Langkah ini akan menampilkan semua file dan folder di proyek Anda
      # persis seperti yang dilihat oleh server GitHub.
      # =================================================================
      - name: Tampilkan Struktur Folder Secara Detail
        run: |
          echo "========================================="
          echo "Menampilkan struktur folder dari direktori root:"
          pwd
          ls -R
          echo "========================================="
 